name: 'webapp1 run'

on:
  push:
    paths:
      - 'webapp1/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp1
    steps:
      - name: echo
        run: npm run echo
