name: 'webapp3 run'

on:
  push:
    paths:
      - 'webapp3/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp3
    steps:
      - name: echo
        run: npm run echo
