name: 'webapp2 release'

on:
  push:
    branches:
      - main
    paths:
      - 'webapp2/**'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
